services:
  - type: web
    name: anonymous-chat-bot
    env: python
    buildCommand: ""
    startCommand: bash start_web.sh
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
