services:
  - type: worker
    name: anonymous-chat-bot
    env: python
    startCommand: python bot.py  # Or your bot's entry point
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
